# Generated by Django 4.2.7 on 2023-12-02 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_city", models.CharField(max_length=64)),
                ("origin_code", models.CharField(max_length=3)),
                ("origin_country", models.CharField(max_length=64)),
                ("destination_city", models.CharField(max_length=64)),
                ("destination_code", models.CharField(max_length=3)),
                ("destination_country", models.CharField(max_length=64)),
                ("depart_time", models.TimeField()),
                ("duration", models.DurationField()),
                ("plane", models.CharField(max_length=24)),
                ("airline", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_class", models.CharField(max_length=20)),
                ("booking_date", models.DateTimeField(default=datetime.datetime.now)),
                ("status", models.CharField(max_length=45)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="mainapp.flight",
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        related_name="flight_tickets", to="mainapp.passenger"
                    ),
                ),
            ],
        ),
    ]
